# Development project infrastructure generated over the Docker
version: "3.4"

services:
  # Database image to run the mysql
  db:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    volumes:
       - mysql_data:/var/lib/mysql
       - .:/app
    env_file:
       - ./env/mysql.env

  # Run the application over HTTP on localhost:8080
  # Nginx
  server:
    build:
      context: ./docker-images/nginx
    links:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./docker-images/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html

  # PHP-FPM with WP dependencies
  wordpress:
    build:
      context: ./docker-images/wp-fpm
    volumes:
      - .:/var/www/html
    env_file:
       - ./env/app.env
       - ./env/xdebug.env
    depends_on:
      - db
      - smtp

  # Test SMTP server
  smtp:
    image: schickling/mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      MAILCATCHER_PORT: 1025

  # Image for install and update project PHP packages.
  wp:
    image: wordpress:cli
    volumes:
      - .:/var/www/html
    env_file:
       - ./env/app.env
    depends_on:
      - db

# Use default Docker volume for database to fix Windows issue that doesn't work with bind volume
volumes:
  mysql_data: